
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type OptionLike, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, type DeployInstantiationOptions, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import PlayChipsContractArtifactJson from '../target/play_chips_contract-PlayChips.json' with { type: 'json' };
export const PlayChipsContractArtifact = loadContractArtifact(PlayChipsContractArtifactJson as NoirCompiledContract);



/**
 * Type-safe interface for contract PlayChips;
 */
export class PlayChipsContract extends ContractBase {

  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, PlayChipsContractArtifact, wallet);
  }



  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): PlayChipsContract {
    return Contract.at(address, PlayChipsContract.artifact, wallet) as PlayChipsContract;
  }


  /**
   * Creates a tx to deploy a new instance of this contract.
   * @param instantiation - Optional address-affecting parameters (salt, deployer / universalDeploy, publicKeys).
   *                       Salt defaults to a random value; the deployer is locked lazily from the first send-time `from`.
   */
  public static deploy(wallet: Wallet, instantiation?: DeployInstantiationOptions) {
    return DeployMethod.create<PlayChipsContract>(
      wallet,
      {
        artifact: PlayChipsContractArtifact,
        postDeployCtor: (instance, wallet) => PlayChipsContract.at(instance.address, wallet),
        args: [],
      },
      instantiation,
    );
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof PlayChipsContract['methods']>(
    opts: { method?: M; wallet: Wallet; instantiation?: DeployInstantiationOptions },
    ...args: Parameters<PlayChipsContract['methods'][M]>
  ) {
    return DeployMethod.create<PlayChipsContract>(
      opts.wallet,
      {
        artifact: PlayChipsContractArtifact,
        postDeployCtor: (instance, wallet) => PlayChipsContract.at(instance.address, wallet),
        args,
        constructorNameOrArtifact: opts.method ?? 'constructor',
      },
      opts.instantiation,
    );
  }



  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return PlayChipsContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(PlayChipsContractArtifactJson as NoirCompiledContract);
  }


  public static get storage(): ContractStorageLayout<'owner' | 'claimed' | 'entries' | 'entry_tables' | 'entry_amounts' | 'table_pool' | 'table_settled' | 'private_balances'> {
      return {
        owner: {
      slot: new Fr(1n),
    },
claimed: {
      slot: new Fr(2n),
    },
entries: {
      slot: new Fr(3n),
    },
entry_tables: {
      slot: new Fr(4n),
    },
entry_amounts: {
      slot: new Fr(5n),
    },
table_pool: {
      slot: new Fr(6n),
    },
table_settled: {
      slot: new Fr(7n),
    },
private_balances: {
      slot: new Fr(8n),
    }
      } as ContractStorageLayout<'owner' | 'claimed' | 'entries' | 'entry_tables' | 'entry_amounts' | 'table_pool' | 'table_settled' | 'private_balances'>;
    }


  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {

    /** claim_private() */
    claim_private: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** contract_owner() */
    contract_owner: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** enter_table(table_id: field, entry_id: field, amount: integer) */
    enter_table: ((table_id: FieldLike, entry_id: FieldLike, amount: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** entry_amount_of(entry_id: field) */
    entry_amount_of: ((entry_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** entry_exists(entry_id: field) */
    entry_exists: ((entry_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** entry_table_of(entry_id: field) */
    entry_table_of: ((entry_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** faucet_amount() */
    faucet_amount: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** has_claimed(owner: struct) */
    has_claimed: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** offchain_receive(messages: struct) */
    offchain_receive: ((messages: { ciphertext: FieldLike[], recipient: AztecAddressLike, tx_hash: OptionLike<FieldLike>, anchor_block_timestamp: (bigint | number) }[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** private_balance_of(owner: struct) */
    private_balance_of: ((owner: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** settle_private(table_id: field, recipients: array, payouts: array) */
    settle_private: ((table_id: FieldLike, recipients: AztecAddressLike[], payouts: (bigint | number)[]) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** setup() */
    setup: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state(scope: struct) */
    sync_state: ((scope: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** table_is_settled(table_id: field) */
    table_is_settled: ((table_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** table_pool_of(table_id: field) */
    table_pool_of: ((table_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };


}
