import { ProtocolDemo } from "@/components/protocol-demo";
import { SiteHeader } from "@/components/site-header";

export default function ProtocolPage() {
  return (
    <main className="site-shell protocol-page">
      <SiteHeader compact />
      <header className="protocol-hero">
        <p className="eyebrow">Protocol, not marketing</p>
        <h1>What is hidden, what is public, and what anyone can recompute.</h1>
        <p>
          Noir Poker uses two different cryptographic mechanisms. Commit–contribute–reveal
          fixes each deck. A Noir circuit proves private bounty statements. They solve different
          problems and make different trust assumptions.
        </p>
      </header>

      <section className="protocol-section" id="deals">
        <div className="section-index"><span>01</span><p>Fair dealing</p></div>
        <div className="protocol-copy">
          <h2>The server cannot wait for every player input and then search for a favorable deck.</h2>
          <p>
            A room begins with a 32-byte server secret and the public value
            <code> SHA256(&quot;NPDEAL01&quot; || room_uuid || hand_no_be || server_secret)</code>.
            Each browser contributes a fresh 32-byte share. The final joining player&apos;s share is
            unknown when the server commitment is fixed.
          </p>
          <p>
            The seed is <code>SHA256(&quot;NPSEED01&quot; || room || hand || count || ordered(seat, share) || server_secret)</code>.
            Seat bytes prevent reordering. The 52 canonical card identifiers are shuffled with
            SHA-256 counter blocks, 32-bit rejection sampling and descending Fisher–Yates swaps.
          </p>
          <ProtocolDemo />
          <div className="protocol-facts">
            <article><span>Before play</span><strong>Commitment and contribution count</strong></article>
            <article><span>During play</span><strong>Seed, secret and other shares remain hidden</strong></article>
            <article><span>After settlement</span><strong>Secret, shares, seed and all 52 positions</strong></article>
          </div>
          <aside>
            <strong>Precise limit</strong>
            <p>
              This is auditable server-authoritative poker, not mental poker. The server still sees
              every card and can abort instead of completing a ceremony. If all entropy providers
              collude with it, the honest-party guarantee disappears. A full mental-poker protocol
              would encrypt and verifiably reshuffle the deck so no dealer ever learns every card.
            </p>
          </aside>
        </div>
      </section>

      <section className="protocol-section" id="bounties">
        <div className="section-index"><span>02</span><p>Private bounties</p></div>
        <div className="protocol-copy">
          <h2>The verifier learns that a catalog objective was completed, but not which objective.</h2>
          <p>
            The browser commits to a private 32-byte secret. After the server returns a nonce, Blake2s
            selects one of eight objective leaves. A three-level Merkle path proves that the hidden leaf
            belongs to the published catalog root.
          </p>
          <div className="circuit-statement">
            <div><span>Public inputs</span><code>mode · hand_tag · seat · commitment · nonce · facts_hash · nullifier · catalog_root</code></div>
            <div><span>Private witness</span><code>secret · facts salt · six facts · objective literals · Merkle siblings</code></div>
          </div>
          <p>
            The draw proof shows that the committed secret selected a valid hidden leaf. The completion
            proof reuses the same public context and shows that the leaf&apos;s true and false literals match
            the server-bound fact commitment. UltraHonk proofs are generated by NoirJS and Barretenberg
            in the player&apos;s browser, then checked by the Rust server and again by every public receipt viewer.
          </p>
          <aside>
            <strong>What “accepted once” means</strong>
            <p>
              The circuit binds a nullifier to the hand, seat and secret. PostgreSQL enforces a unique
              nullifier and the server awards exactly 20 points in the same transaction. A receipt viewer
              independently proves the cryptographic statement; it does not independently audit the entire database.
            </p>
          </aside>
        </div>
      </section>

      <section className="protocol-section">
        <div className="section-index"><span>03</span><p>Run it yourself</p></div>
        <div className="protocol-copy verifier-commands">
          <h2>Verification is a behavior in the product, not a download button.</h2>
          <p>Every audit and bounty URL runs locally in the browser. The same checks are available as source-controlled scripts.</p>
          <code>npm --prefix apps/web run deal:verify -- audit.json</code>
          <code>npm --prefix apps/web run proof:verify -- receipt.json</code>
          <code>cargo test --workspace</code>
          <p className="protocol-meta">Noir 1.0.0-beta.26 · Barretenberg 5.2.0 · UltraHonk · Blake2s · SHA-256</p>
        </div>
      </section>
    </main>
  );
}
